version: '3.9'
services:
  web:
    image: portainer/portainer:latest
    container_name: portainer
    restart: always
    ports:
      - ${APP_PORT}:9000
    networks:
      - default
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
