version: '3.9'
services:
  web:
    image: portainer/portainer:latest
    container_name: portainer
    restart: always
    ports:
      - ${HTTP_PORT}:9000
      - ${HTTPS_PORT}:9443
      - ${AFENT_PORT}:8000
    networks:
      - default
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: docker_portainer_network
    driver: bridge

volumes:
  data:
    name: docker_portainer_data
    driver: local
