services:
  portainer:
    container_name: ${PORTAINER_CONTAINER_NAME}
    image: ${PORTAINER_IMAGE_NAME}:${PORTAINER_IMAGE_VERSION}
    restart: ${RESTART_POLICY}
    environment:
      - TZ=${TIMEZONE}
    ports:
      - ${PORTAINER_HTTP_PORT}:9000
      - ${PORTAINER_HTTPS_PORT}:9443
      - ${PORTAINER_AGENT_PORT}:8000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default

networks:
  default:
    name: ${PORTAINER_CONTAINER_NAME}_network
    driver: bridge

volumes:
  portainer_data:
    name: ${PORTAINER_CONTAINER_NAME}_data
    driver: local